export const RESET_STATE = 'RESET_STATE'
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'

export const SET_USERS = 'SET_USERS'
export const SET_USER = 'SET_USER'
export const SET_TODOS = 'SET_TODOS'
export const SET_TODO = 'SET_TODO'
export const SET_POSTS = 'SET_POSTS'
export const SET_POST = 'SET_POST'
export const SET_COMMENTS = 'SET_COMMENTS'
export const SET_COMMENT = 'SET_COMMENT'
export const SET_ALBUMS = 'SET_ALBUMS'
export const SET_ALBUM = 'SET_ALBUM'
export const SET_PHOTOS = 'SET_PHOTOS'
export const SET_PHOTO = 'SET_PHOTO'
